### ISSUE TITLE
Multistrike in CharacterStats is absent.

### ISSUE THREAD

**Issue by ghost** [briandek/WowDotNetAPI#75]
Hi,

the file [WowDotNetAPI/Explorers/Models/CharacterStats.cs](https://github.com/briandek/WowDotNetAPI/blob/master/Explorers/Models/CharacterStats.cs) does not contain multistrike.

From the json file return by the following url: 

`https://eu.api.battle.net/wow/character/REALM/CHARACTER?fields=stats&locale=LOCALE&apikey=API_KEY`

we can see:

```
[...]
"multistrike": 23.984848,
"multistrikeRating": 23.984848,
"multistrikeRatingBonus": 23.984848,
[...]
```

Probably add this code may fix the problem:

``` csharp
[DataMember(Name = "multistrike")]
        public double Multistrike { get; set; }
// etc...
```

Is it possible to add Multistrike to this ? Even if it isn't possible, I will try to make a pull request with fonctionnal and tested code.

PS: Sorry for my poor english level, english is not my mothertongue.

**Comment by mjdean1994** [comment]
I've got some time this afternoon. I'll see about fixing this up.
