### ISSUE TITLE
Sample project ERROR

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [briandek/WowDotNetAPI#83]
Hello, I try WowDotNetAPI sample, but get error...

Additional information: Could not load type 'WowDotNetAPI.WowExplorer' from assembly 'WowDotNetAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Thank you for help.

**Comment by LairdStreak** [comment]
you need to open the solution to build the assembly not just the test project.
