### ISSUE TITLE
Should the JsonUtil support caching of requests

### ISSUE THREAD

**Issue by ge0metrix** [briandek/WowDotNetAPI#90]
In order to limit the number of calls to the API endpoints, would enabling caching in JsonUtility.cs be beneficial?
 
Or maybe it should be implemented at a different layer?

**Comment by LairdStreak** [comment]
Good question. Needs to be smart as character data achievements etc are constantly changing but items usualy remain much the same untill new patches drop.

I some-how feel this should be handled outside of data extraction perhaps creating a local cache via database or file system.

**Comment by jsassner** [comment]
Imho, that should be outside the API.

**Comment by ge0metrix** [comment]
Reason I was suggesting within the API is that in the API layer you have access to the httpresponse headers which include the caching info. 

But no worries either way was just an Idea that I had.

**Comment by LairdStreak** [comment]
Closing as wont implement as discussed this should be handled outside of the scraper.
